<?php

/**
 * @var \Pedidos\Model\Pedidos $pedido
 * @var int $id
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$title = 'Delete pedido';
$url   = $this->url('Pedidos', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que deseja excluir o pedido
    "<?= $this->escapeHtml($this->pedido->getNome()) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $this->pedido->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>
