<?php

declare(strict_types=1);

use Clientes\Constantes\ConstantesClientes;

if ($this->action === 'edit') {
//    echo $this->formEditPedidos(
//        $this->form,
//        'Editar Pedido',
//        ConstantesPedidos::ROUTE,
//        $this->id_pedido
//    );
} elseif ($this->action === 'add') {
    echo $this->formAddClientes(
        $this->clienteForm,
        'Adicionar Cliente',
        ConstantesClientes::ROUTE
    );
} else {
    $clientes = $this->pedidos;
    $searchTerm = $this->searchTerm;

    $this->headTitle('Clientes');

    echo '<h1 class="mb-4">Clientes</h1>';

    echo $this->barraPesquisa($this->pesquisaForm);

    echo $this->tabelaClientes($this->filters);
}