<?php

declare(strict_types=1);

use Clientes\Constantes\ConstantesClientes;

if ($this->action === 'edit') {
    echo $this->formEditClientes(
        $this->clienteForm,
        'Editar cliente',
        ConstantesClientes::ROUTE,
        $this->cliente_id
    );
} elseif ($this->action === 'add') {
    echo $this->formAddClientes(
        $this->clienteForm,
        'Adicionar Cliente',
        ConstantesClientes::ROUTE
    );
} elseif ($this->action === 'delete') {
    echo $this->helperDeleteClientes(
        'Excluir Clientes',
        ConstantesClientes::ROUTE,
        $this->cliente
    );
} else {
    $searchTerm = $this->searchTerm;

    $this->headTitle('Clientes');

    echo '<h1 class="mb-4">Clientes</h1>';

    echo $this->barraPesquisa($this->pesquisaForm);

    echo $this->tabelaClientes($this->filters);
}