<?php
$title = 'Editar Pedido';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>

<?php
$form = $this->form;
$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control');
$nome->setAttribute('placeholder', 'Nome do Pedido');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$submit->setAttribute('value', 'Salvar');

$form->setAttribute('action', $this->url('escada', [
        'action' => 'edit',
        'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($nome) ?>
        <?= $this->formElement($nome) ?>
        <?= $this->formElementErrors()->render($nome, ['class' => 'help-block text-danger']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();