<?php

declare(strict_types=1);

$this->headTitle('Pedidos');

echo '<h1 class="mb-4">Pedidos</h1>';

echo $this->barraPesquisa([
    'showAddButton' => false,
    'campos' => [
        'nome' => [
            'label' => 'Nome',
            'placeholder' => 'Digite o nome...'
        ],
        'idade' => [
            'label' => 'Idade',
            'placeholder' => 'Digite a idade...'
        ]
    ]
]);

echo $this->tabelaPedidos($this->pedidos);

echo $this->mensagensAlert($this->pedidos, $this->searchTerm);